---
- name: Install MySQL
  hosts: all
  gather_facts: false

- name: Install and Configure mysqld
  hosts: mysqld
  gather_facts: false
  roles:
    - 'mysqld'

- name: Configure clients
  hosts: clients
  gather_facts: false
  roles:
     - 'mysql_client'
