---
- name: Install MySQLd
  hosts: all
  gather_facts: false

- name: Install and Configure MySQL
  hosts: all
  gather_facts: false
  roles:
    - 'mysql'

- name: Configure clients
  hosts: all
  gather_facts: false
  roles:
     - 'mysql_client'
