---
- name: Create tmp directory
  file:
    path: '{{ mysql_tmp_dir }}'
    state: directory
    mode: 0755
  tags: [ client ]

- name: Acquire Java Connector
  get_url:
    url: '{{ mysql_connector_url }}'
    dest: '{{ mysql_tmp_dir }}/{{ mysql_connector_tarball }}'
    checksum: md5:6419f5a73c76991d73e27a93babca263
  tags: [ client ]

- name: Extract Java Connector
  unarchive:
    src: '{{ mysql_tmp_dir }}/{{ mysql_connector_tarball }}'
    dest: '{{ mysql_tmp_dir }}'
    remote_src: 'yes'
    creates: '{{ mysql_tmp_dir }}/{{ mysql_connector_name }}'
  tags: [ client ]

- name: Ensure /usr/share/java exists
  become: true
  file:
    path: '{{ mysql_connector_path }}'
    state: directory
    mode: 0755
  tags: [ client ]

- name: Copy Connector J
  become: true
  shell: 'cp {{ mysql_connector_srcpath }}/{{ mysql_connector_jarfile }} {{ mysql_connector_path }}/'
  tags: [ client ]

- name: Link Mysql Connector jar
  become: true
  file:
    src: '{{ mysql_connector_path }}/{{ mysql_connector_jarfile }}'
    dest: '{{ mysql_connector_path }}/{{ mysql_connector }}.jar'
    state: link
  tags: [ client ]

- name: Cleanup state
  become: true
  file:
    path: '{{ mysql_tmp_dir }}'
    state: absent
  tags: [ client ]
