---
- name: Install Mysql 5.7 Community Repository (Debian/Ubuntu)
  become: true
  tags: [ server5, client5 ]
  block:
    - name: Install prereqs (Debian/Ubuntu)
      ansible.builtin.apt:
        name: '{{ common_apt_packages }}'
        state: present
    - name: Set apt source file
      ansible.builtin.copy:
        src: 'mysql5.list'
        dest: '/etc/apt/sources.list.d/mysql.list'
        mode: '0644'
    - name: Add Mysql Community Repo Key
      ansible.builtin.apt_key:
        data: "{{ lookup('file', 'mysql.gpg') }}"
        state: present
    - name: Install MySQL 5.7 Client Packages (Debian/Ubuntu)
      ansible.builtin.apt:
        name: '{{ common_apt_mysql5_client_packages }}'
        update_cache: true
        state: present
    - name: Install MySQL Python Connector (Debian/Ubuntu)
      ansible.builtin.apt:
        deb: '{{ mysql_python_connector_deb }}'
    - name: Install python3 mysql package
      ansible.builtin.pip:
        name: 'PyMySQL'
        state: present

- name: Install MySQL 8.0 Community Repository (Debian/Ubuntu)
  become: true
  tags: [ server8, client8 ]
  block:
    - name: Install apt prereqs (Debian/Ubuntu)
      ansible.builtin.apt:
        name: '{{ common_apt_packages }}'
        state: present
    - name: Configure apt source file
      ansible.builtin.copy:
        src: 'mysql8.list'
        dest: '/etc/apt/sources.list.d/mysql.list'
        mode: '0644'
    - name: Add Mysql Community Repo Key
      ansible.builtin.apt_key:
        data: "{{ lookup('file', 'mysql.gpg') }}"
        state: present
    - name: Install MySQL 8.0 Client Packages (Debian/Ubuntu)
      ansible.builtin.apt:
        name: '{{ common_apt_mysql8_client_packages }}'
        update_cache: true
        state: present
    - name: Install python3 mysql package
      ansible.builtin.pip:
        name: 'PyMySQL'
        state: present
