---
- name: Install Mysql 5.7 Community Repository (Debian/Ubuntu)
  block:
  - name: Install prereqs (Debian/Ubuntu)
    apt:
      name: '{{ apt_packages }}'
      state: present
  - name: Set apt source file
    copy:
      src: 'mysql5.list'
      dest: '/etc/apt/sources.list.d/mysql.list'
      mode: 0644
  - name: Add Mysql Community Repo Key
    apt_key:
      data: "{{ lookup('file', 'mysql.gpg') }}"
      state: present
  - name: Install MySQL 5.7 Client Packages (Debian/Ubuntu)
    apt:
      name: '{{ apt_mysql5_client_packages }}'
      update_cache: yes
      state: present
  - name: Install MySQL Python Connector (Debian/Ubuntu)
    apt:
      deb: '{{ mysql_python_connector_deb }}'
  - name: Install python3 mysql package
    pip:
      name: 'PyMySQL'
      state: present
  become: true
  tags: [ server5, client5 ]
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install MySQL 8.0 Community Repository (Debian/Ubuntu)
  block:
  - name: Install apt prereqs (Debian/Ubuntu)
    apt:
      name: '{{ apt_packages }}'
      state: present
  - name: Configure apt source file
    copy:
      src: 'mysql8.list'
      dest: '/etc/apt/sources.list.d/mysql.list'
      mode: 0644
  - name: Add Mysql Community Repo Key
    apt_key:
      data: "{{ lookup('file', 'mysql.gpg') }}"
      state: present
  - name: Install MySQL 8.0 Client Packages (Debian/Ubuntu)
    apt:
      name: '{{ apt_mysql8_client_packages }}'
      update_cache: yes
      state: present
  - name: Install python3 mysql package
    pip:
      name: 'PyMySQL'
      state: present
  become: true
  tags: [ server8, client8 ]
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
