---
- name: Existing mysql datadir
  become: true
  stat:
    path: '{{ mysql_data_dir }}/mysql'
  register: mystat
  tags: [ server5, server8 ]

- name: mysql datadir stat
  debug: 
    var: mystat
  tags: [ server5, server8 ]

- name: Create tmp directory
  file:
    path: '{{ mysql_tmp_dir }}'
    state: directory
    mode: 0755
  tags: [ client5, client8 ]

- name: Ensure /usr/share/java exists
  become: true
  file:
    path: '{{ mysql_connector_path }}'
    state: directory
    mode: 0755
  tags: [ client5, client8 ]

- include: install-rhel.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- include: install-ubuntu.yml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Cleanup state
  become: true
  file:
    path: '{{ mysql_tmp_dir }}'
    state: absent
  tags: [ client5, client8 ]
