---
- name: Existing mysql datadir
  become: true
  stat:
    path: '{{ mysql_data_dir }}/mysql'
  register: mystat
  tags: [ server ]

- name: mysql datadir stat
  debug: 'var=mystat'
  tags: [ server ]

- name: Remove unwanted packages
  yum:
    name: '{{ yum_remove_packages }}'
    state: absent
  become: true
  tags: [ server, client ]

- name: Install Mysql Community Repo
  yum:
    name: '{{ mysql_community_rpm_uri }}'
    state: present
  become: true
  tags: [ server, client ]

- name: Install Client Packages
  yum:
    name: '{{ yum_mysql_client_packages }}'
    state: present
  become: true
  tags: [ client ]
