---
- name: Install MySQL Server Packages (RHEL/CentOS)
  become: true
  tags: [ server5, server8 ]
  ansible.builtin.yum:
    name: '{{ common_yum_mysql_server_packages }}'
    state: present

- name: Set Master Config 5.7
  become: true
  when: inventory_hostname in groups['master']
  tags: [ server5 ]
  ansible.builtin.template:
    src: mysqld.cnf
    dest: /etc/my.cnf
  vars:
    mysql_server_id: 1

- name: Set Master Config 8.0
  become: true
  when: inventory_hostname in groups['master']
  tags: [ server8 ]
  ansible.builtin.template:
    src: mysqld8.cnf
    dest: /etc/my.cnf
  vars:
    mysql_server_id: 1

- name: Set Slave Config 5.7
  become: true
  when: inventory_hostname in groups['slave']
  tags: [ server5 ]
  ansible.builtin.template:
    src: mysqld.cnf
    dest: /etc/my.cnf
  vars:
    mysql_server_id: 2

- name: Set Slave Config 8.0
  become: true
  when: inventory_hostname in groups['slave']
  tags: [ server8 ]
  ansible.builtin.template:
    src: mysqld8.cnf
    dest: /etc/my.cnf
  vars:
    mysql_server_id: 2

- name: Initialize and Start Mysqld
  tags: [ server5, server8 ]
  when: not mystat.stat.exists
  block:
    - name: Initialize mysql
      become: true
      ansible.builtin.shell: 'mysqld --initialize-insecure --user=mysql'
    - name: Start mysqld (RHEL/CentOS)
      become: true
      ansible.builtin.service:
        name: 'mysqld'
        state: 'started'
        enabled: 'yes'
    - name: Set root password
      become: true
      ansible.builtin.shell: "mysql -u root --skip-password -e \"ALTER USER root@localhost IDENTIFIED BY '{{ mysql_root_password }}'\""

- name: Set my.cnf password file
  tags: [ server5, server8 ]
  ansible.builtin.template:
    src: mypw.cnf
    dest: .my.cnf

- name: Mysql Root accounts
  tags: [ server5, server8 ]
  community.mysql.mysql_user:
    login_user: 'root'
    login_password: '{{ mysql_root_password }}'
    login_unix_socket: '{{ mysql_unix_socket }}'
    name: 'root'
    password: '{{ mysql_root_password }}'
    host: '{{ item }}'
    priv: '*.*:ALL,GRANT'
    state: present
  with_items: '{{ mysql_master_hosts }}'
